version: "3"
services:
  tangoql:
    build: .
    restart: always
    command: /bin/bash -c "source activate graphql && adev runserver tangogql/aioserver.py --app-factory=dev_run --port=5004"
    ports:
      - "5004:5004"
    volumes:
      - .:/python3-taurus-core/web-maxiv-graphql
    environment:
      - TANGO_HOST=w-v-kitslab-csdb-0:10000

      # If this is not set, the output of python is delayed and only shows when the docker container restarts
      - PYTHONUNBUFFERED=1
  auth:
    image: webjive-auth
    ports:
      - "8080:8080"
    environment:
      - "REDIS_HOST=redis"
    volumes:
      - "./.env:/var/app/.env"
  redis:
    image: redis
    ports:
      - "6379:6379"
