version: "3"
services:
  tangoql:
    build: .
    restart: always
    ports:
      - "5004:5004"
    volumes:
      - .:/python3-taurus-core/web-maxiv-graphql
    environment:
      - TANGO_HOST=w-v-kitslab-csdb-0:10000
